// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#ifndef _UI_COMP_WIFIICON_H
#define _UI_COMP_WIFIICON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT WifiIcon
#define UI_COMP_WIFIICON_WIFIICON 0
#define _UI_COMP_WIFIICON_NUM 1
lv_obj_t * ui_WifiIcon_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
