// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#ifndef _UI_COMP_NOTIFICATIONBAR_H
#define _UI_COMP_NOTIFICATIONBAR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT NotificationBar
#define UI_COMP_NOTIFICATIONBAR_NOTIFICATIONBAR 0
#define UI_COMP_NOTIFICATIONBAR_TIMECONTAINER 1
#define UI_COMP_NOTIFICATIONBAR_TIMECONTAINER_TIME 2
#define UI_COMP_NOTIFICATIONBAR_WIFIICONCONTAINER 3
#define UI_COMP_NOTIFICATIONBAR_WIFIICONCONTAINER_WIFIICON 4
#define UI_COMP_NOTIFICATIONBAR_BATTERYTEXT 5
#define UI_COMP_NOTIFICATIONBAR_BATTERYCONTAINER 6
#define UI_COMP_NOTIFICATIONBAR_BATTERYCONTAINER_BATTERY 7
#define UI_COMP_NOTIFICATIONBAR_BATTERYCONTAINER_CHARGINGICON 8
#define _UI_COMP_NOTIFICATIONBAR_NUM 9
lv_obj_t * ui_NotificationBar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
