// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#include "ui.h"

// COMPONENT WifiIcon

lv_obj_t * ui_WifiIcon_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_WifiIcon;
    cui_WifiIcon = lv_img_create(comp_parent);
    lv_img_set_src(cui_WifiIcon, &ui_img_wifiicon_png);
    lv_obj_set_width(cui_WifiIcon, lv_pct(100));
    lv_obj_set_height(cui_WifiIcon, lv_pct(100));
    lv_obj_set_align(cui_WifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_WifiIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_WifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_WIFIICON_NUM);
    children[UI_COMP_WIFIICON_WIFIICON] = cui_WifiIcon;
    lv_obj_add_event_cb(cui_WifiIcon, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_WifiIcon, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_WifiIcon_create_hook(cui_WifiIcon);
    return cui_WifiIcon;
}

