// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#include "ui.h"

// COMPONENT NotificationBar

lv_obj_t * ui_NotificationBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_NotificationBar;
    cui_NotificationBar = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_NotificationBar);
    lv_obj_set_width(cui_NotificationBar, 128);
    lv_obj_set_height(cui_NotificationBar, 16);
    lv_obj_set_x(cui_NotificationBar, 0);
    lv_obj_set_y(cui_NotificationBar, -72);
    lv_obj_set_align(cui_NotificationBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_NotificationBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_NotificationBar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_NotificationBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_NotificationBar, lv_color_hex(0x000D1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_NotificationBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TimeContainer;
    cui_TimeContainer = lv_obj_create(cui_NotificationBar);
    lv_obj_remove_style_all(cui_TimeContainer);
    lv_obj_set_width(cui_TimeContainer, 49);
    lv_obj_set_height(cui_TimeContainer, lv_pct(100));
    lv_obj_set_align(cui_TimeContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_TimeContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_TimeContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Time;
    cui_Time = lv_label_create(cui_TimeContainer);
    lv_obj_set_height(cui_Time, 12);
    lv_obj_set_width(cui_Time, lv_pct(55));
    lv_obj_set_align(cui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Time, "10:15");
    lv_obj_set_style_text_font(cui_Time, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Time, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_WifiIconContainer;
    cui_WifiIconContainer = lv_obj_create(cui_NotificationBar);
    lv_obj_remove_style_all(cui_WifiIconContainer);
    lv_obj_set_width(cui_WifiIconContainer, 25);
    lv_obj_set_height(cui_WifiIconContainer, 16);
    lv_obj_set_x(cui_WifiIconContainer, 3);
    lv_obj_set_y(cui_WifiIconContainer, -10);
    lv_obj_set_align(cui_WifiIconContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_WifiIconContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_WifiIcon;
    cui_WifiIcon = lv_img_create(cui_WifiIconContainer);
    lv_img_set_src(cui_WifiIcon, &ui_img_wifiicon_png);
    lv_obj_set_width(cui_WifiIcon, 28);
    lv_obj_set_height(cui_WifiIcon, 16);
    lv_obj_set_x(cui_WifiIcon, 3);
    lv_obj_set_y(cui_WifiIcon, 0);
    lv_obj_set_align(cui_WifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_WifiIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_WifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_WifiIcon, 192);

    lv_obj_t * cui_BatteryText;
    cui_BatteryText = lv_label_create(cui_NotificationBar);
    lv_obj_set_width(cui_BatteryText, 25);
    lv_obj_set_height(cui_BatteryText, 12);
    lv_obj_set_x(cui_BatteryText, 8);
    lv_obj_set_y(cui_BatteryText, -8);
    lv_obj_set_align(cui_BatteryText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_BatteryText, "100%");
    lv_obj_set_style_text_align(cui_BatteryText, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_BatteryText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BatteryText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BatteryText, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BatteryText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BatteryText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BatteryContainer;
    cui_BatteryContainer = lv_obj_create(cui_NotificationBar);
    lv_obj_remove_style_all(cui_BatteryContainer);
    lv_obj_set_width(cui_BatteryContainer, 22);
    lv_obj_set_height(cui_BatteryContainer, 16);
    lv_obj_set_x(cui_BatteryContainer, -26);
    lv_obj_set_y(cui_BatteryContainer, 0);
    lv_obj_set_align(cui_BatteryContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_BatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Battery;
    cui_Battery = lv_bar_create(cui_BatteryContainer);
    lv_bar_set_value(cui_Battery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_Battery, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Battery, 20);
    lv_obj_set_height(cui_Battery, 8);
    lv_obj_set_align(cui_Battery, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(cui_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Battery, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ChargingIcon;
    cui_ChargingIcon = lv_img_create(cui_BatteryContainer);
    lv_img_set_src(cui_ChargingIcon, &ui_img_chargingicon_png);
    lv_obj_set_width(cui_ChargingIcon, 16);
    lv_obj_set_height(cui_ChargingIcon, 16);
    lv_obj_set_align(cui_ChargingIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ChargingIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_ChargingIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_ChargingIcon, 192);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NOTIFICATIONBAR_NUM);
    children[UI_COMP_NOTIFICATIONBAR_NOTIFICATIONBAR] = cui_NotificationBar;
    children[UI_COMP_NOTIFICATIONBAR_TIMECONTAINER] = cui_TimeContainer;
    children[UI_COMP_NOTIFICATIONBAR_TIMECONTAINER_TIME] = cui_Time;
    children[UI_COMP_NOTIFICATIONBAR_WIFIICONCONTAINER] = cui_WifiIconContainer;
    children[UI_COMP_NOTIFICATIONBAR_WIFIICONCONTAINER_WIFIICON] = cui_WifiIcon;
    children[UI_COMP_NOTIFICATIONBAR_BATTERYTEXT] = cui_BatteryText;
    children[UI_COMP_NOTIFICATIONBAR_BATTERYCONTAINER] = cui_BatteryContainer;
    children[UI_COMP_NOTIFICATIONBAR_BATTERYCONTAINER_BATTERY] = cui_Battery;
    children[UI_COMP_NOTIFICATIONBAR_BATTERYCONTAINER_CHARGINGICON] = cui_ChargingIcon;
    lv_obj_add_event_cb(cui_NotificationBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_NotificationBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_NotificationBar_create_hook(cui_NotificationBar);
    return cui_NotificationBar;
}

