// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#ifndef UI_DAILYQUOTE_H
#define UI_DAILYQUOTE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DailyQuote
extern void ui_DailyQuote_screen_init(void);
extern void ui_DailyQuote_screen_destroy(void);
extern lv_obj_t * ui_DailyQuote;
extern lv_obj_t * ui_DQNotificationBar;
extern lv_obj_t * ui_QuoteContainer;
extern lv_obj_t * ui_QuoteLabel;
extern lv_obj_t * ui_Navigation2;
extern lv_obj_t * ui_Tab7;
extern lv_obj_t * ui_SensorTabLabel2;
extern lv_obj_t * ui_Tab4;
extern lv_obj_t * ui_QuoteTabLabel2;
extern lv_obj_t * ui_Tab5;
extern lv_obj_t * ui_EmailTabLabel2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_DailyQuote;
extern lv_obj_t * uic_QuoteLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

