// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#include "ui.h"

lv_obj_t * uic_QuoteLabel;
lv_obj_t * uic_DailyQuote;
lv_obj_t * ui_DailyQuote = NULL;
lv_obj_t * ui_DQNotificationBar = NULL;
lv_obj_t * ui_QuoteContainer = NULL;
lv_obj_t * ui_QuoteLabel = NULL;
lv_obj_t * ui_Navigation2 = NULL;
lv_obj_t * ui_Tab7 = NULL;
lv_obj_t * ui_SensorTabLabel2 = NULL;
lv_obj_t * ui_Tab4 = NULL;
lv_obj_t * ui_QuoteTabLabel2 = NULL;
lv_obj_t * ui_Tab5 = NULL;
lv_obj_t * ui_EmailTabLabel2 = NULL;
// event funtions

// build funtions

void ui_DailyQuote_screen_init(void)
{
    ui_DailyQuote = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DailyQuote, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DQNotificationBar = ui_NotificationBar_create(ui_DailyQuote);
    lv_obj_set_x(ui_DQNotificationBar, 0);
    lv_obj_set_y(ui_DQNotificationBar, -72);

    ui_QuoteContainer = lv_obj_create(ui_DailyQuote);
    lv_obj_remove_style_all(ui_QuoteContainer);
    lv_obj_set_height(ui_QuoteContainer, 132);
    lv_obj_set_width(ui_QuoteContainer, lv_pct(100));
    lv_obj_set_x(ui_QuoteContainer, 0);
    lv_obj_set_y(ui_QuoteContainer, 2);
    lv_obj_set_align(ui_QuoteContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_QuoteContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_QuoteContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_QuoteContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_QuoteContainer, lv_color_hex(0x00132B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QuoteContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_QuoteContainer, lv_color_hex(0x00325B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_QuoteContainer, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_QuoteContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_QuoteContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_QuoteContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_QuoteContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QuoteLabel = lv_label_create(ui_QuoteContainer);
    lv_obj_set_width(ui_QuoteLabel, lv_pct(100));
    lv_obj_set_height(ui_QuoteLabel, lv_pct(100));
    lv_obj_set_x(ui_QuoteLabel, 13);
    lv_obj_set_y(ui_QuoteLabel, 0);
    lv_obj_set_align(ui_QuoteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_QuoteLabel, "Quote:\n<ERROR RECIEVING DAILY QUOTE>: Check your connection");
    lv_obj_set_style_text_font(ui_QuoteLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Navigation2 = lv_obj_create(ui_DailyQuote);
    lv_obj_remove_style_all(ui_Navigation2);
    lv_obj_set_height(ui_Navigation2, 12);
    lv_obj_set_width(ui_Navigation2, lv_pct(100));
    lv_obj_set_x(ui_Navigation2, 0);
    lv_obj_set_y(ui_Navigation2, 74);
    lv_obj_set_align(ui_Navigation2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Navigation2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Navigation2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Navigation2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navigation2, lv_color_hex(0x000D1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navigation2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab7 = lv_obj_create(ui_Navigation2);
    lv_obj_remove_style_all(ui_Tab7);
    lv_obj_set_width(ui_Tab7, 42);
    lv_obj_set_height(ui_Tab7, 12);
    lv_obj_set_align(ui_Tab7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tab7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Tab7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SensorTabLabel2 = lv_label_create(ui_Tab7);
    lv_obj_set_width(ui_SensorTabLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorTabLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorTabLabel2, 10);
    lv_obj_set_y(ui_SensorTabLabel2, -1);
    lv_obj_set_align(ui_SensorTabLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SensorTabLabel2, "Sensor");
    lv_obj_set_style_text_font(ui_SensorTabLabel2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SensorTabLabel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SensorTabLabel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SensorTabLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SensorTabLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab4 = lv_obj_create(ui_Navigation2);
    lv_obj_remove_style_all(ui_Tab4);
    lv_obj_set_width(ui_Tab4, 44);
    lv_obj_set_height(ui_Tab4, 12);
    lv_obj_set_align(ui_Tab4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tab4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Tab4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tab4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tab4, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QuoteTabLabel2 = lv_label_create(ui_Tab4);
    lv_obj_set_width(ui_QuoteTabLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_QuoteTabLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_QuoteTabLabel2, 10);
    lv_obj_set_y(ui_QuoteTabLabel2, 0);
    lv_obj_set_align(ui_QuoteTabLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_QuoteTabLabel2, "Quote");
    lv_obj_set_style_text_font(ui_QuoteTabLabel2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab5 = lv_obj_create(ui_Navigation2);
    lv_obj_remove_style_all(ui_Tab5);
    lv_obj_set_width(ui_Tab5, 42);
    lv_obj_set_height(ui_Tab5, 12);
    lv_obj_set_align(ui_Tab5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tab5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Tab5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EmailTabLabel2 = lv_label_create(ui_Tab5);
    lv_obj_set_width(ui_EmailTabLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmailTabLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EmailTabLabel2, 10);
    lv_obj_set_y(ui_EmailTabLabel2, 0);
    lv_obj_set_align(ui_EmailTabLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmailTabLabel2, "Email");
    lv_obj_set_style_text_font(ui_EmailTabLabel2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_DailyQuote = ui_DailyQuote;
    uic_QuoteLabel = ui_QuoteLabel;

}

void ui_DailyQuote_screen_destroy(void)
{
    if(ui_DailyQuote) lv_obj_del(ui_DailyQuote);

    // NULL screen variables
    uic_DailyQuote = NULL;
    ui_DailyQuote = NULL;
    ui_DQNotificationBar = NULL;
    ui_QuoteContainer = NULL;
    uic_QuoteLabel = NULL;
    ui_QuoteLabel = NULL;
    ui_Navigation2 = NULL;
    ui_Tab7 = NULL;
    ui_SensorTabLabel2 = NULL;
    ui_Tab4 = NULL;
    ui_QuoteTabLabel2 = NULL;
    ui_Tab5 = NULL;
    ui_EmailTabLabel2 = NULL;

}
