// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#ifndef UI_EMAILSUMMARY_H
#define UI_EMAILSUMMARY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EmailSummary
extern void ui_EmailSummary_screen_init(void);
extern void ui_EmailSummary_screen_destroy(void);
extern lv_obj_t * ui_EmailSummary;
extern lv_obj_t * ui_ESNotificationBar;
extern lv_obj_t * ui_EmailSummaryContainer;
extern lv_obj_t * ui_EmailSummaryLabel;
extern lv_obj_t * ui_Navigation3;
extern lv_obj_t * ui_Tab10;
extern lv_obj_t * ui_SensorTabLabel3;
extern lv_obj_t * ui_Tab6;
extern lv_obj_t * ui_QuoteTabLabel3;
extern lv_obj_t * ui_Tab8;
extern lv_obj_t * ui_EmailTabLabel3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_EmailSummary;
extern lv_obj_t * uic_EmailSummaryContainer;
extern lv_obj_t * uic_EmailSummaryLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

