// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#include "ui.h"

lv_obj_t * uic_EmailSummaryLabel;
lv_obj_t * uic_EmailSummaryContainer;
lv_obj_t * uic_EmailSummary;
lv_obj_t * ui_EmailSummary = NULL;
lv_obj_t * ui_ESNotificationBar = NULL;
lv_obj_t * ui_EmailSummaryContainer = NULL;
lv_obj_t * ui_EmailSummaryLabel = NULL;
lv_obj_t * ui_Navigation3 = NULL;
lv_obj_t * ui_Tab10 = NULL;
lv_obj_t * ui_SensorTabLabel3 = NULL;
lv_obj_t * ui_Tab6 = NULL;
lv_obj_t * ui_QuoteTabLabel3 = NULL;
lv_obj_t * ui_Tab8 = NULL;
lv_obj_t * ui_EmailTabLabel3 = NULL;
// event funtions

// build funtions

void ui_EmailSummary_screen_init(void)
{
    ui_EmailSummary = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EmailSummary, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ESNotificationBar = ui_NotificationBar_create(ui_EmailSummary);
    lv_obj_set_x(ui_ESNotificationBar, 0);
    lv_obj_set_y(ui_ESNotificationBar, -72);

    ui_EmailSummaryContainer = lv_obj_create(ui_EmailSummary);
    lv_obj_remove_style_all(ui_EmailSummaryContainer);
    lv_obj_set_height(ui_EmailSummaryContainer, 132);
    lv_obj_set_width(ui_EmailSummaryContainer, lv_pct(100));
    lv_obj_set_x(ui_EmailSummaryContainer, 0);
    lv_obj_set_y(ui_EmailSummaryContainer, 2);
    lv_obj_set_align(ui_EmailSummaryContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EmailSummaryContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EmailSummaryContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_EmailSummaryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EmailSummaryContainer, lv_color_hex(0x00132B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmailSummaryContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_EmailSummaryContainer, lv_color_hex(0x00325B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_EmailSummaryContainer, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_EmailSummaryContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_EmailSummaryContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_EmailSummaryContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_EmailSummaryContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmailSummaryLabel = lv_label_create(ui_EmailSummaryContainer);
    lv_obj_set_width(ui_EmailSummaryLabel, lv_pct(100));
    lv_obj_set_height(ui_EmailSummaryLabel, lv_pct(100));
    lv_obj_set_x(ui_EmailSummaryLabel, 13);
    lv_obj_set_y(ui_EmailSummaryLabel, 0);
    lv_obj_set_align(ui_EmailSummaryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmailSummaryLabel, "Email Summery: \n<ERROR RECIEVING EMAIL SUMMERY>: Check your connection");
    lv_obj_set_style_text_font(ui_EmailSummaryLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Navigation3 = lv_obj_create(ui_EmailSummary);
    lv_obj_remove_style_all(ui_Navigation3);
    lv_obj_set_height(ui_Navigation3, 12);
    lv_obj_set_width(ui_Navigation3, lv_pct(100));
    lv_obj_set_x(ui_Navigation3, 0);
    lv_obj_set_y(ui_Navigation3, 74);
    lv_obj_set_align(ui_Navigation3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Navigation3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Navigation3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Navigation3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navigation3, lv_color_hex(0x000D1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navigation3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab10 = lv_obj_create(ui_Navigation3);
    lv_obj_remove_style_all(ui_Tab10);
    lv_obj_set_width(ui_Tab10, 42);
    lv_obj_set_height(ui_Tab10, 12);
    lv_obj_set_align(ui_Tab10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tab10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Tab10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SensorTabLabel3 = lv_label_create(ui_Tab10);
    lv_obj_set_width(ui_SensorTabLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorTabLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorTabLabel3, 10);
    lv_obj_set_y(ui_SensorTabLabel3, -1);
    lv_obj_set_align(ui_SensorTabLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SensorTabLabel3, "Sensor");
    lv_obj_set_style_text_font(ui_SensorTabLabel3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SensorTabLabel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SensorTabLabel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SensorTabLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SensorTabLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab6 = lv_obj_create(ui_Navigation3);
    lv_obj_remove_style_all(ui_Tab6);
    lv_obj_set_width(ui_Tab6, 44);
    lv_obj_set_height(ui_Tab6, 12);
    lv_obj_set_align(ui_Tab6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tab6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Tab6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_QuoteTabLabel3 = lv_label_create(ui_Tab6);
    lv_obj_set_width(ui_QuoteTabLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_QuoteTabLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_QuoteTabLabel3, 10);
    lv_obj_set_y(ui_QuoteTabLabel3, 0);
    lv_obj_set_align(ui_QuoteTabLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_QuoteTabLabel3, "Quote");
    lv_obj_set_style_text_font(ui_QuoteTabLabel3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab8 = lv_obj_create(ui_Navigation3);
    lv_obj_remove_style_all(ui_Tab8);
    lv_obj_set_width(ui_Tab8, 42);
    lv_obj_set_height(ui_Tab8, 12);
    lv_obj_set_align(ui_Tab8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tab8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Tab8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tab8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tab8, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmailTabLabel3 = lv_label_create(ui_Tab8);
    lv_obj_set_width(ui_EmailTabLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmailTabLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EmailTabLabel3, 10);
    lv_obj_set_y(ui_EmailTabLabel3, 0);
    lv_obj_set_align(ui_EmailTabLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmailTabLabel3, "Email");
    lv_obj_set_style_text_font(ui_EmailTabLabel3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_EmailSummary = ui_EmailSummary;
    uic_EmailSummaryContainer = ui_EmailSummaryContainer;
    uic_EmailSummaryLabel = ui_EmailSummaryLabel;

}

void ui_EmailSummary_screen_destroy(void)
{
    if(ui_EmailSummary) lv_obj_del(ui_EmailSummary);

    // NULL screen variables
    uic_EmailSummary = NULL;
    ui_EmailSummary = NULL;
    ui_ESNotificationBar = NULL;
    uic_EmailSummaryContainer = NULL;
    ui_EmailSummaryContainer = NULL;
    uic_EmailSummaryLabel = NULL;
    ui_EmailSummaryLabel = NULL;
    ui_Navigation3 = NULL;
    ui_Tab10 = NULL;
    ui_SensorTabLabel3 = NULL;
    ui_Tab6 = NULL;
    ui_QuoteTabLabel3 = NULL;
    ui_Tab8 = NULL;
    ui_EmailTabLabel3 = NULL;

}
