// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_NotificationBar;
extern lv_obj_t * ui_TimeContainer;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_WifiIconContainer;
extern lv_obj_t * ui_WifiIcon1;
extern lv_obj_t * ui_BatteryText;
extern lv_obj_t * ui_BatteryContainer;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_ChargingIcon;
extern lv_obj_t * ui_Body;
extern lv_obj_t * ui_IlluminationContainer;
extern lv_obj_t * ui_IlluminationLabel;
extern lv_obj_t * ui_IlluminationImage;
extern lv_obj_t * ui_IlluminationUnit;
extern lv_obj_t * ui_IlluminationBody;
extern lv_obj_t * ui_Illumination;
extern lv_obj_t * ui_AirQualityContainer;
extern lv_obj_t * ui_AirQuality1;
extern lv_obj_t * ui_AirQualityImage;
extern lv_obj_t * ui_AirQualityUnit;
extern lv_obj_t * ui_AirQualityBody;
extern lv_obj_t * ui_AirQuality;
extern lv_obj_t * ui_RelativeHumidityContainer;
extern lv_obj_t * ui_RelativeHumidityLabel;
extern lv_obj_t * ui_RelativeHumidityImage;
extern lv_obj_t * ui_RelativeHumidityUnit;
extern lv_obj_t * ui_RelativeHumidityBody;
extern lv_obj_t * ui_RelativeHumidity;
extern lv_obj_t * ui_TemperatureContainer;
extern lv_obj_t * ui_TemperatureLabel;
extern lv_obj_t * ui_TemperatureImage;
extern lv_obj_t * ui_TemperatureUnit;
extern lv_obj_t * ui_TemperatureBody;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_PressureContainer;
extern lv_obj_t * ui_PressureLabel;
extern lv_obj_t * ui_PressureImage;
extern lv_obj_t * ui_PressureUnit;
extern lv_obj_t * ui_PressureBody;
extern lv_obj_t * ui_Pressure;
extern lv_obj_t * ui_SoundContainer;
extern lv_obj_t * ui_SoundLabel;
extern lv_obj_t * ui_SoundImage;
extern lv_obj_t * ui_SoundUnit;
extern lv_obj_t * ui_SoundBody;
extern lv_obj_t * ui_Sound;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TimeContainer;
extern lv_obj_t * uic_Time;
extern lv_obj_t * uic_WifiIconContainer;
extern lv_obj_t * uic_ChargingIcon;
extern lv_obj_t * uic_IlluminationLabel;
extern lv_obj_t * uic_IlluminationImage;
extern lv_obj_t * uic_Illumination;
extern lv_obj_t * uic_AirQualityContainer;
extern lv_obj_t * uic_AirQuality1;
extern lv_obj_t * uic_AirQuality;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

