// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_NotificationBar;
extern lv_obj_t * ui_TimeContainer;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_WifiIconContainer;
extern lv_obj_t * ui_WifiIcon1;
extern lv_obj_t * ui_BatteryText;
extern lv_obj_t * ui_BatteryContainer;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_ChargingIcon;
extern lv_obj_t * ui_Body;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TimeContainer;
extern lv_obj_t * uic_Time;
extern lv_obj_t * uic_WifiIconContainer;
extern lv_obj_t * uic_ChargingIcon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

