// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#include "ui.h"

lv_obj_t * uic_ChargingIcon;
lv_obj_t * uic_WifiIconContainer;
lv_obj_t * uic_Time;
lv_obj_t * uic_TimeContainer;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_NotificationBar = NULL;
lv_obj_t * ui_TimeContainer = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_WifiIconContainer = NULL;
lv_obj_t * ui_WifiIcon1 = NULL;
lv_obj_t * ui_BatteryText = NULL;
lv_obj_t * ui_BatteryContainer = NULL;
lv_obj_t * ui_Battery = NULL;
lv_obj_t * ui_ChargingIcon = NULL;
lv_obj_t * ui_Body = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotificationBar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_NotificationBar);
    lv_obj_set_width(ui_NotificationBar, 128);
    lv_obj_set_height(ui_NotificationBar, 16);
    lv_obj_set_x(ui_NotificationBar, 0);
    lv_obj_set_y(ui_NotificationBar, -72);
    lv_obj_set_align(ui_NotificationBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NotificationBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_NotificationBar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NotificationBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NotificationBar, lv_color_hex(0x000D1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NotificationBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeContainer = lv_obj_create(ui_NotificationBar);
    lv_obj_remove_style_all(ui_TimeContainer);
    lv_obj_set_width(ui_TimeContainer, 49);
    lv_obj_set_height(ui_TimeContainer, lv_pct(100));
    lv_obj_set_align(ui_TimeContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TimeContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TimeContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time = lv_label_create(ui_TimeContainer);
    lv_obj_set_height(ui_Time, 12);
    lv_obj_set_width(ui_Time, lv_pct(55));
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "10:15");
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Time, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIconContainer = lv_obj_create(ui_NotificationBar);
    lv_obj_remove_style_all(ui_WifiIconContainer);
    lv_obj_set_width(ui_WifiIconContainer, 25);
    lv_obj_set_height(ui_WifiIconContainer, 16);
    lv_obj_set_x(ui_WifiIconContainer, 3);
    lv_obj_set_y(ui_WifiIconContainer, -10);
    lv_obj_set_align(ui_WifiIconContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiIconContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiIcon1 = lv_img_create(ui_WifiIconContainer);
    lv_img_set_src(ui_WifiIcon1, &ui_img_wifiicon_png);
    lv_obj_set_width(ui_WifiIcon1, 28);
    lv_obj_set_height(ui_WifiIcon1, 16);
    lv_obj_set_x(ui_WifiIcon1, 3);
    lv_obj_set_y(ui_WifiIcon1, 0);
    lv_obj_set_align(ui_WifiIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WifiIcon1, 192);

    ui_BatteryText = lv_label_create(ui_NotificationBar);
    lv_obj_set_width(ui_BatteryText, 25);
    lv_obj_set_height(ui_BatteryText, 12);
    lv_obj_set_x(ui_BatteryText, 8);
    lv_obj_set_y(ui_BatteryText, -8);
    lv_obj_set_align(ui_BatteryText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryText, "100%");
    lv_obj_set_style_text_align(ui_BatteryText, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatteryText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatteryText, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatteryText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatteryText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryContainer = lv_obj_create(ui_NotificationBar);
    lv_obj_remove_style_all(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryContainer, 22);
    lv_obj_set_height(ui_BatteryContainer, 16);
    lv_obj_set_x(ui_BatteryContainer, -26);
    lv_obj_set_y(ui_BatteryContainer, 0);
    lv_obj_set_align(ui_BatteryContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery = lv_bar_create(ui_BatteryContainer);
    lv_bar_set_value(ui_Battery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery, 20);
    lv_obj_set_height(ui_Battery, 8);
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargingIcon = lv_img_create(ui_BatteryContainer);
    lv_img_set_src(ui_ChargingIcon, &ui_img_chargingicon_png);
    lv_obj_set_width(ui_ChargingIcon, 16);
    lv_obj_set_height(ui_ChargingIcon, 16);
    lv_obj_set_align(ui_ChargingIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargingIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChargingIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ChargingIcon, 192);

    ui_Body = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Body);
    lv_obj_set_width(ui_Body, 128);
    lv_obj_set_height(ui_Body, 139);
    lv_obj_set_x(ui_Body, 0);
    lv_obj_set_y(ui_Body, 5);
    lv_obj_set_align(ui_Body, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Body, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 2);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    uic_TimeContainer = ui_TimeContainer;
    uic_Time = ui_Time;
    uic_WifiIconContainer = ui_WifiIconContainer;
    uic_ChargingIcon = ui_ChargingIcon;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_NotificationBar = NULL;
    uic_TimeContainer = NULL;
    ui_TimeContainer = NULL;
    uic_Time = NULL;
    ui_Time = NULL;
    uic_WifiIconContainer = NULL;
    ui_WifiIconContainer = NULL;
    ui_WifiIcon1 = NULL;
    ui_BatteryText = NULL;
    ui_BatteryContainer = NULL;
    ui_Battery = NULL;
    uic_ChargingIcon = NULL;
    ui_ChargingIcon = NULL;
    ui_Body = NULL;
    ui_Spinner1 = NULL;

}
