// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AuraLink

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_notificationbar = NULL;
lv_obj_t * ui_Battery = NULL;
lv_obj_t * ui_body = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_notificationbar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_notificationbar);
    lv_obj_set_width(ui_notificationbar, 128);
    lv_obj_set_height(ui_notificationbar, 10);
    lv_obj_set_x(ui_notificationbar, 0);
    lv_obj_set_y(ui_notificationbar, -75);
    lv_obj_set_align(ui_notificationbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_notificationbar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_notificationbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_notificationbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_notificationbar, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notificationbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery = lv_bar_create(ui_notificationbar);
    lv_bar_set_value(ui_Battery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery, 20);
    lv_obj_set_height(ui_Battery, 6);
    lv_obj_set_x(ui_Battery, 56);
    lv_obj_set_y(ui_Battery, -63);
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_Battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_body = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_body);
    lv_obj_set_width(ui_body, 128);
    lv_obj_set_height(ui_body, 150);
    lv_obj_set_x(ui_body, 0);
    lv_obj_set_y(ui_body, 5);
    lv_obj_set_align(ui_body, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_body, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_body, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_body, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 2);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_notificationbar = NULL;
    ui_Battery = NULL;
    ui_body = NULL;
    ui_Spinner1 = NULL;

}
